name: dom_stub
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
#  lib_name: any
 code_transformers: any
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
transformers:
- dom_stub
- test/pub_serve:
    $include: test/**_test.dart
